---
- include: cleanup.yml
  when: "{{rpmfusion__state == 'absent' and ansible_distribution|lower == 'fedora'}}"

- include: setup.yml
  when: "{{rpmfusion__state == 'present' and ansible_distribution|lower == 'fedora'}}"
