---
- name: install the rpmfusion repo packages
  dnf: name={{ item }}
       state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/{{ rpmfusion__free }}-{{ fedora_current }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/{{ rpmfusion__nonfree }}-{{ fedora_current }}.noarch.rpm
