 # ansible local -m setup --tree /tmp/facts
 # ansible-playbook workpc_playbook.yml --ask-sudo-pass
- hosts: local
  tags:
    - software
  vars_files:
    - group_vars/local/main.yml
    - group_vars/base/main.yml
#    - "group_vars/{{ansible__nodename}}/main.yml"
  roles:
#    - role: oh-my-zsh
#      sudo: false
#    - role: godev
#      sudo: false
#    - role: font-awesome
#      sudo: false
#    - role: font-hack
#      sudo: false
#    - role: font-source-code-pro
#      sudo: false
#    - role: i3
#      sudo: yes
#    - role: docker
#      sudo: true
#    - role: virtualbox
#      sudo: true
#    - role: nodejs
#      sudo: false
#    - role: jvm
#      sudo: true
#    - role: gnome-terminal
#      sudo: false
#    - role: emacs
#      sudo: false
#    - role: rpmfusion
#      sudo: yes
#    - role: chrome
#      sudo: yes
#    - role: spotify
#      sudo: yes
#    - role: software
#      sudo: yes
#    - role: racket
#      sudo: yes
#    - role: mysql-workbench
#      sudo: yes
#    - role: elementary-theme
#      sudo: yes
#    - role: mono
#      sudo: false
    - role: fsharp
      sudo: false