---
 #ansible-playbook workpc_playbook.yml --user=pseudo --ask-sudo-pass
- name: install the rpmfusion repo packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm

- name: install | base software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{wrk_pkgs}}"
