---
- name: determining if java copy is already installed
  stat:
    path: "{{jvm__inst_dir}}"
  register: st_jvm_dir

- debug: msg="{{jvm__inst_dir}} already exists - Remove first before attempting a (re)install"
  failed_when: 1
  when: st_jvm_dir is defined and st_jvm_dir.stat.exists

- name: ensuring necessary directories exist
  file:
    state: directory
    path: "{{item.path}}"
    mode: "{{item.mode}}"
    recurse: true
  with_items:
    - {path: "{{ jvm__tmp_dir }}", mode: "0755" }

- set_fact:
    java_pkg_fname: "{{jvm__type}}-{{jvm__fullver}}.tgz"

# Using wget because of the need to set a cookie to download java
- name: Download software
  shell: "wget -qO {{ item.dest }} {{item.flags}} {{ item.uri }}"
  args:
    creates: "{{ item.dest }}"
  with_items:
    - { uri: "{{jvm__uri}}", dest: "{{ jvm__tmp_dir }}/{{java_pkg_fname}}", flags: "--header 'Cookie: oraclelicense=accept-securebackup-cookie'"}

- name: create java destination directory
  file:
    path: "{{jvm__dest_dir}}"
    state: directory

- name: extract java
  unarchive:
    src: "{{ jvm__tmp_dir }}/{{ java_pkg_fname }}"
    dest: "{{ jvm__dest_dir }}"

- name: rename java directory
  shell:  "mv {{jvm__extracted_dirname}} {{jvm__inst_dirname}}"
  args:
    chdir: "{{ jvm__dest_dir }}"

- name: install java binary alternatives
  alternatives:
    name: "{{item.name}}"
    link: "{{item.link}}"
    path: "{{item.path}}"
  with_items:
    - { name: "java", link: "/usr/bin/java", path: "{{ jvm__inst_dir }}/bin/java" }
    - { name: "javac", link: "/usr/bin/javac", path: "{{ jvm__inst_dir }}/bin/javac" }
    - { name: "javah", link: "/usr/bin/javah", path: "{{ jvm__inst_dir }}/bin/javah" }

- name: select correct alternatives
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items:
    - {name: "java", path: "{{ jvm__inst_dir }}/bin/java" }
    - {name: "javac", path: "{{ jvm__inst_dir}}/bin/javac" }
    - {name: "javah", path: "{{ jvm__inst_dir}}/bin/javah" }


#src=/file/to/link/to dest=/path/to/symlink owner=foo group=foo state=link
- name: install links to alternatives links
  file:
    src: "/etc/alternatives/{{ item.name }}"
    dest: "/usr/bin/{{ item.name }}"
    state: link
    owner: root
    group: root
    mode: 0755
  with_items:
    - { name: "java" }
    - { name: "javac" }
    - { name: "javah" }

- name: Remove temporary files
  file:
    state: absent
    path: "{{jvm__tmp_dir}}"
