---

- name: fedora | adding repo
  get_url:
    url: http://negativo17.org/repos/fedora-spotify.repo
    dest: /etc/yum.repos.d/spotify.repo
    mode: 0644
    owner: root
    group: root

- name: fedora | install chrome
  dnf:
    name: spotify-client
    state: present
