---
- name: fedora | install | install ZSH shell
  dnf: name=zsh state=present
  when: "{{ansible_distribution|lower == 'fedora'}}"
  sudo: yes

- name: debian/ubuntu | install | install ZSH shell
  apt: name=zsh state=present cache_valid_time=3600 update_cache=true
  when: "{{ansible_os_family|lower == 'debian'}}"

- name: install | clone Oh-My-ZSH
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ozsh__home }}"
    depth: 1

- stat: path="{{ ozsh__rc_dist }}"
  register: dist_zshrc_st

- name: processing | determining if ~/.zshrc.dist is from oh-my-zsh
  shell: "{{ 'grep $ZSH/oh-my-zsh.sh ' + ozsh__rc_dist }}"
  failed_when: 0
  changed_when: 0
  when: dist_zshrc_st.stat.islnk is defined
  register: dist_zshrc_grep

- set_fact:
    doinst_dist_zshrc: "{{dist_zshrc_grep|skipped or dist_zshrc_grep.rc != 0}}"

- name: config | installing ~/.zshrc.dist
  shell: cp "{{ ozsh__home }}/templates/zshrc.zsh-template" "{{ ozsh__rc_dist }}"
  when: doinst_dist_zshrc

# Grep for zshrc_template_tag, if not present, back up and install template
- stat: path="{{ ozsh__rc_dist }}"
  register: zshrc_st

- name: processing | determining if ~/.zshrc is from this role
  shell: "{{ 'grep ' + ozsh__rc_grep_key + ' ' + ozsh__rc }}"
  failed_when: 0
  changed_when: 0
  when: zshrc_st.stat.islnk is defined
  register: zshrc_grep

- set_fact:
    do_backup_zshrc: "{{zshrc_grep is defined and zshrc_grep.skipped|default(false) == false and zshrc_grep.rc != 0}}"

- name: config | appending '.old.<date here>' to old .zshrc file
  shell: cp "{{ ozsh__rc }}" "{{ ozsh__rc }}.old.`date -I`"
  when: do_backup_zshrc

- name: config | create .zshcfg.dist directory
  file:
    state: directory
    path: "{{ozsh__cfg_dist}}"

- name: config | installing new .zshrc
  template:
    src: .zshrc.j2
    dest: "{{ ozsh__rc }}"
    mode: 0600

- name: processing | determining path to zsh
  shell: grep '/zsh$' /etc/shells | tail -1
  changed_when: 0
  register: zsh_shell_path

# regarding sudo: only way I can avoid it failing due to it wanting to ask the
# user for his password.
- name: config | changing your shell to zsh
  user: name="{{ansible_user_id}}" shell="{{zsh_shell_path.stdout}}"
  sudo: yes
