---
ozsh__home: "{{ansible_user_dir}}/.oh-my-zsh"

# Directory in which to place *.zsh files which will be sourced during
# session initialization.
ozsh__cfg_dist: "{{ansible_user_dir}}/.zshcfg.dist"

ozsh__cfg_usr: "{{ansible_user_dir}}/.zshcfg.override"

# The config which wraps Oh-My-ZSH's settings in a few additional
# settings such as the ability to read, init.d-style environment files
# !! other roles WILL depend on this
ozsh__rc: "{{ansible_user_dir}}/.zshrc"
# The config file which Oh-My-ZSH intends to install
ozsh__rc_dist: "{{ozsh__rc}}.dist"

#Key which we'll be using to figure out if an existing ~/.zshrc file is ours
# -- ensure there's no spaces here
ozsh__rc_grep_key: "pseudos-ansible-zsh-cfg"
