---

- name: fedora | add docker repo
  template:
    src: "fedora/{{item.src}}"
    dest: "{{item.dst}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "docker.repo.j2", dst: "/etc/yum.repos.d/docker.repo"}

- name: fedora | install docker
  dnf:
    name: docker-engine
    state: present

#Needed to communicate with insecure registries, among other things
- name: fedora | template docker sysconfig file
  template:
    src: "fedora/{{item.src}}"
    dest: "{{item.dst}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "etc-sysconfig-docker.j2", dst: "/etc/sysconfig/docker" }

- name: fedora | install firewall rule fix
  copy:
    src: "fedora/{{ item.name }}"
    dest: "{{ item.dstdir }}/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { name: "docker-iptbl-fix", dstdir: "/usr/lib/systemd/scripts/", mode: "0755" }
    - { name: "docker-iptbl-fix.service", dstdir: "/usr/lib/systemd/system/", mode: "0644" }
    - { name: "docker.service", dstdir: "/lib/systemd/system/", mode: "0644" }

- name: fedora | enable docker firewall fix service
  service: name=docker-iptbl-fix enabled=yes state=restarted
