---

- name: fedora | add docker repo
  template:
    src: fedora/docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: fedora | install docker
  dnf:
    name: docker-engine
    state: present

- name: fedora | install firewall rule fix
  copy:
    src: "fedora/{{ item.name }}"
    dest: "{{ item.dstdir }}/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { name: "docker-iptbl-fix", dstdir: "/usr/lib/systemd/scripts/", mode: "0755" }
    - { name: "docker-iptbl-fix.service", dstdir: "/usr/lib/systemd/system/", mode: "0644" }

- name: fedora | enable docker firewall fix service
  service: name=docker-iptbl-fix enabled=yes state=restarted
