---
# Remove the software itself and the repo which provided it
- name: fedora | remove software
  dnf:
    name: "{{item}}"
    state: absent
  with_items:
    - mysql-community-release
    - mysql-workbench-community
  sudo: yes
